### PR TITLE
Fixed Leaderboard Sorting issue

### LINKED ISSUE #18: Change ranking criteria for leaderboard
With PR kunaljain0212/git-init-FOSS-API#2 merged, the API returns the number of easy, medium and hard issues that a student has resolved. Our current ranking system ranks on the basis of the total score, and in case of a tie, the students are sorted in alphabetical order. However, with the newly added data about the different types of issues and their numbers we can make our ranking system a lot better.

We need to rank students according to the following criteria, in that order (i.e. lowest criterion gets the lowest precedence):
* Total score
* Number of hard issues solved
* Number of medium issues solved
* Number of easy issues solved
* Alphabetical order of name

With this system, in case of a tie, the student who has solved more difficult issues will be ranked higher.

### PR DESCRIPTION
**Pull request by AkshithGandla**
I have tried to fix the ranking issues of the leaderboard. Now the ranking is given in the following order (lowest criterion gets the lowest precedence)

- Total score
- Number of hard issues solved
- Number of medium issues solved
- Number of easy issues solved
- Alphabetical order of name

This closes #18

### CODE REVIEW

File: src/stores/leaderboard.js [hunk 1]
```diff
@@ -139,7 +139,11 @@ export const rankify = () => {
       p.name = titleCase(p.name);
     });
     lb.sort((a, b) => (b.name > a.name ? -1 : 1));
+    lb.sort((a,b) => b.easy - a.easy);
+    lb.sort((a,b) => b.medium - a.medium);
```
Comment (hs2361) [inline src/stores/leaderboard.js:143]: Please fix the formatting as `(a, b)` (whitespace before b).

**Review by hs2361 — CHANGES_REQUESTED** [review]
Thanks a lot for your PR! We really appreciate you taking the time to contribute to the project. Please make the suggested changes, and then I'll merge your PR.
